# Generated by Django 2.0.5 on 2018-06-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180606_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Female', 'female'), ('Not-specified', 'not-specified'), ('Male', 'male')], max_length=80, null=True),
        ),
    ]
