# Generated by Django 2.0.5 on 2018-06-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180615_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Not-specified', 'not-specified'), ('Male', 'male'), ('Female', 'female')], max_length=80, null=True),
        ),
    ]
