# Generated by Django 2.0.5 on 2018-06-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180617_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Not-specified', 'not-specified')], max_length=80, null=True),
        ),
    ]
