# Generated by Django 2.0.5 on 2018-06-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20180619_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('not-specified', 'Not-specified'), ('female', 'Female')], max_length=80, null=True),
        ),
    ]
