# Generated by Django 2.0.5 on 2018-06-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20180619_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('not-specified', 'Not-specified'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
