# Generated by Django 2.0.5 on 2019-01-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20190121_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('not-specified', 'Not-specified'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
