# Generated by Django 2.0.5 on 2019-01-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20190128_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not-specified'), ('female', 'Female'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
